### ISSUE TITLE
Issue with a dependency's license

### ISSUE THREAD

**Issue by audricschiltknecht** [jochenvg/go-udev#9]
Hello,

The project makes use of the https://github.com/jkeiser/iter module, which unfortunately has no license, thus making it proprietary software.
I've opened an issue (https://github.com/jkeiser/iter/issues/1) with the maintainer to ask them to clarify the license, but if there is no answer from them or should they choose to not use an opensource license, would you agree to replace the problematic license in the repo?
Code of the module looks quite simple, and I don't think there would be an issue with having some similar code included in the repo or hosted as a new deps (with a proper license).

Thanks!

**Comment by jochenvg** [comment]
Yes that sounds sensible. Care to send a PR?

**Comment by jkeiser** [comment]
I have made the license MIT since that is one of the more open licenses. Not sure what the Go license is, but I don't mind using a different one if necessary. I haven't touched the module for a while but as you noted, it's simple and should be solid.

**Comment by audricschiltknecht** [comment]
Thanks a lot!
